### PR TITLE
fix: remove timeout on update visible items + simplify resizing

### LINKED ISSUE #360: Changing tabs triggers map style update after hard coded 500ms

### PR DESCRIPTION
**Pull request by QuCMGisaia**
Fix #360

### CODE REVIEW

File: src/app/components/arlas-wui-root/arlas-wui-root.component.ts [hunk 1]
```diff
@@ -286,14 +284,8 @@ export class ArlasWuiRootComponent implements OnInit, AfterViewInit, OnDestroy {
...
-          this.adjustCoordinates();
-        });
-      /** trigger 'resize' event after toggling sidenav  */
-      this.sidenavService.sideNavState
-        .pipe(takeUntil(this._onDestroy$))
-        .subscribe(res => {
-          this.onSideNavChange = res;
-          window.dispatchEvent(new Event('resize'));
+          this.adjustComponentsSize();
+          this.updateVisibleItems();
```
Comment (sebbousquet) [inline src/app/components/arlas-wui-root/arlas-wui-root.component.ts:288]: `adjustComponentsSize()` contains a call to `updateVisibleItems`
I think you can remove `this.updateVisibleItems()` here

File: src/app/components/arlas-wui-root/arlas-wui-root.component.ts [hunk 2]
```diff
@@ -679,6 +666,7 @@ export class ArlasWuiRootComponent implements OnInit, AfterViewInit, OnDestroy {
         });
 
       if (!!this.previewListContrib) {
+        // Weird ? Shouldn't we just take it once ?
```
Comment (MohamedHamouGisaia) [inline src/app/components/arlas-wui-root/arlas-wui-root.component.ts:669]: Yes i agree, it's weird

File: src/assets/tour/tour_en.json [hunk 3]
```diff
@@ -1,30 +1,6 @@
...
-      "content": "Here you can search anything to filter the data.",
-      "target": "arlas-search",
-      "placement": "bottom"
-    },
-    {
-      "title": "Analytics and Filters",
-      "content": "This board gives you a global view of your data thanks to the different analytics. <br> You can interact with them directly to filter the data.",
-      "target": ".arlas-analytics--container",
-      "placement": "right"
-    },
```
[the remark this answers is not in the document]
Comment (QuCMGisaia) [reply src/assets/tour/tour_en.json]: This is a mistake, I was checking another issue and forgot to remove my modifications

**Review by sebbousquet — APPROVED** [review]

**Review by MohamedHamouGisaia — APPROVED** [review]
